[metadata]
name = home-work
version = 0.1.0
description = Financial tracker with currency conversion
author = Anastasia Danilicheva

[options]
packages = find:
install_requires =
    requests>=2.31.0
    python-dotenv>=1.0.0

[options.extras_require]
dev =
    pytest>=7.0.0
    pytest-cov>=4.0.0
    mypy>=1.0.0
    flake8>=6.0.0
